### ISSUE TITLE
now we need cookies

### ISSUE THREAD

**Issue by krisvida** [LisaCozCus/teamturing-k-l#3]
- [x] sub task 1
- [ ] sub task 2
- [ ] sub task 3

**Comment by krisvida** [comment]
-[] sub task 1

**Comment by krisvida** [comment]
- [ ] sub task

**Comment by krisvida** [comment]
#5 @LisaCozCus

**Comment by krisvida** [comment]
dupe #3

**Comment by krisvida** [comment]
blocked by #5

**Comment by LisaCozCus** [comment]
[DPIA Template.docx](https://github.com/LisaCozCus/teamturing-k-l/files/2449904/DPIA.Template.docx)
